/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddsimoba;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author juse
 */
public class FormularioModificacionPartida extends javax.swing.JInternalFrame {

    private String idPartida;
    
    /**
     * Creates new form FormularioModificacionPartida
     */
    public FormularioModificacionPartida(String idPartida,String tipo, String descripcion) {
        initComponents();
        setValores(idPartida,tipo,descripcion);
    }
    
    public void setValores(String idPartida, String tipo, String descripcion){
        this.descripcion.setText(descripcion);
        this.tipo.setText(tipo);
        this.idPartida=idPartida;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        Bmodificar = new javax.swing.JButton();

        setTitle("Modificacion de partidas");
        setName("Modificacion de Partidas"); // NOI18N

        jLabel2.setText("tipo");

        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });

        jLabel3.setText("descripcion");

        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });

        Bmodificar.setText("Modificar");
        Bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Bmodificar)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(Bmodificar)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Modificacion de Partidas");
        getAccessibleContext().setAccessibleDescription("Modificacion de Partidas");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void BmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarActionPerformed
          ConexionDB conexion = new ConexionDB();
        
        //Preparo la consulta
        PreparedStatement pstm = null;   
       
        //He de extraer todos los valores de los campos Para añadirlos a la base de datos
        String id = this.idPartida;
        String type = this.tipo.getText();
        String description = this.descripcion.getText();
        
        String sqlQuery = "UPDATE partida SET tipo = ?, descripcion = ? WHERE idpartida= ?";
               
        //Preparo la sentencia a ejecutar.
        try{
        pstm = conexion.con.prepareStatement(sqlQuery);
        
        pstm.setString(1, type);
        pstm.setString(2, description);
        pstm.setString(3, id);
        
        int resultado = pstm.executeUpdate();
        
        if(resultado ==1){
            
            JOptionPane.showMessageDialog(null, "Se ha actualizado la fila correctamente", "Alerta ", JOptionPane.INFORMATION_MESSAGE);
        }else{
            throw new RuntimeException("No se pudo actualizar la fila la fila");
        }
            
        }catch(SQLException ex){
            ex.printStackTrace(System.out);
            throw new RuntimeException(ex);
        }finally{
            
            try{
                if(pstm!=null) pstm.close();
                if(conexion.con!=null) conexion.cerrarConexionDB();
            }catch(SQLException ex){
                ex.printStackTrace(System.out);
                throw new RuntimeException(ex);
            }
        }
          
        this.dispose();//Cerramos la ventana y llama además al recolector de basura para que no se quede por medio
    }//GEN-LAST:event_BmodificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bmodificar;
    private javax.swing.JTextField descripcion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
