/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddsimoba;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author domin
 */
public class FormularioModificacionUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioAltaUsuario
     */
    public FormularioModificacionUsuario(String nombre, String idequipo, String pass, String correo, String fech, String server, String saldo, String karma) {
        initComponents();
        setValores(nombre, idequipo,pass,correo,fech, server,saldo,karma);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        correoUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        equipoUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        serverUsuario = new javax.swing.JComboBox<>();
        bModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        karma = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificación de Usuario");
        setToolTipText("");

        jLabel1.setText("Usuario");

        nombreUsuario.setEditable(false);
        nombreUsuario.setToolTipText("");

        jLabel2.setText("Pass");

        passUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Correo");

        correoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoUsuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Fech. Nac");

        jLabel5.setText("Equipo");

        jLabel6.setText("Servidor");

        serverUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EU", "NA", "LPL", "LCK" }));

        bModificar.setText("Modificar");
        bModificar.setToolTipText("");
        bModificar.setActionCommand("");
        bModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarActionPerformed(evt);
            }
        });

        jLabel7.setText("Saldo");

        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        jLabel8.setText("Karma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(correoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombreUsuario)
                                .addComponent(passUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechUsuario)
                            .addComponent(saldo)
                            .addComponent(karma))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(equipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(correoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(serverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fechUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(karma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bModificar)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void setValores(String nombre, String idequipo, String pass, String correo, String fech, String server, String saldo, String karma){
        
        this.nombreUsuario.setText(nombre);
        this.equipoUsuario.setText(idequipo);
        this.passUsuario.setText(pass);
        this.correoUsuario.setText(correo);
        this.fechUsuario.setText(fech);
        this.karma.setText(karma);
        this.saldo.setText(saldo);
        
        switch(server){
            case "EU":this.serverUsuario.setSelectedIndex(0); break;
            case "NA":this.serverUsuario.setSelectedIndex(1); break;
            case "LPL":this.serverUsuario.setSelectedIndex(2); break;
            case "LCK":this.serverUsuario.setSelectedIndex(3); break;
            
        }
        
        
        
    }
    
    
    
    private void bModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarActionPerformed

        ConexionDB conexion = new ConexionDB();
        
        //Preparo la consulta
        PreparedStatement pstm = null;   
       
        //He de extraer todos los valores de los campos Para añadirlos a la base de datos
        String user = this.nombreUsuario.getText();
        String pass = this.passUsuario.getText();
        String email = this.correoUsuario.getText();
        String equipo = this.equipoUsuario.getText();
        String fech = this.fechUsuario.getText();
        String servidor = this.serverUsuario.getSelectedItem().toString();
        String karma1 = this.karma.getText();
        String saldo1 = this.saldo.getText();
        
        String sqlQuery = "UPDATE cuentapertenece SET idequipo= ?, contrasena = ?, correo = ?, fec_nac = ?, servidor = ?, saldo = ?, karma = ? WHERE nombre= ?";
               
        //Preparo la sentencia a ejecutar.
        try{
        pstm = conexion.con.prepareStatement(sqlQuery);
        
        pstm.setString(1, equipo);
        pstm.setString(2, pass);
        pstm.setString(3, email);
        pstm.setString(4, fech);
        pstm.setString(5, servidor);
        pstm.setString(6, saldo1);
        pstm.setString(7, karma1);
        pstm.setString(8, user);
        
        int resultado = pstm.executeUpdate();
        
        if(resultado ==1){
            
            JOptionPane.showMessageDialog(null, "Se ha actualizado la fila correctamente", "Alerta ", JOptionPane.INFORMATION_MESSAGE);
        }else{
            throw new RuntimeException("No se pudo actualizar la fila la fila");
        }
            
        }catch(SQLException ex){
            ex.printStackTrace(System.out);
            throw new RuntimeException(ex);
        }finally{
            
            try{
                if(pstm!=null) pstm.close();
                if(conexion.con!=null) conexion.cerrarConexionDB();
            }catch(SQLException ex){
                ex.printStackTrace(System.out);
                throw new RuntimeException(ex);
            }
        }
          
        this.dispose();//Cerramos la ventana y llama además al recolector de basura para que no se quede por medio
        
        
    }//GEN-LAST:event_bModificarActionPerformed

    private void passUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passUsuarioActionPerformed

    private void correoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoUsuarioActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bModificar;
    private javax.swing.JTextField correoUsuario;
    private javax.swing.JTextField equipoUsuario;
    private javax.swing.JTextField fechUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField karma;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JTextField passUsuario;
    private javax.swing.JTextField saldo;
    private javax.swing.JComboBox<String> serverUsuario;
    // End of variables declaration//GEN-END:variables
}
