/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddsimoba;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author jesus
 */
public class FormularioBusquedaComplDenuncias extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioBusquedaComplDenuncias
     */
    public FormularioBusquedaComplDenuncias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masDenunciado = new javax.swing.JButton();
        masDenunciante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        masAntiguo = new javax.swing.JButton();
        masReciente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        equipoBusc = new javax.swing.JTextField();
        buscarEquipo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Búsqueda Avanzada de Denuncias");

        masDenunciado.setText("Usuario más denunciado");
        masDenunciado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masDenunciadoActionPerformed(evt);
            }
        });

        masDenunciante.setText("Usuario más denunciante");
        masDenunciante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masDenuncianteActionPerformed(evt);
            }
        });

        jLabel1.setText("Búsqueda cronológica");

        masAntiguo.setText("Más antiguo");
        masAntiguo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masAntiguoActionPerformed(evt);
            }
        });

        masReciente.setText("Más reciente");
        masReciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masRecienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Búsqueda por equipo");

        buscarEquipo.setText("OK");
        buscarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(masDenunciado)
                        .addGap(26, 26, 26)
                        .addComponent(masDenunciante))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(masAntiguo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(masReciente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equipoBusc, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masDenunciado)
                    .addComponent(masDenunciante))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masReciente)
                    .addComponent(masAntiguo)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(equipoBusc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarEquipo))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masDenuncianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masDenuncianteActionPerformed
        // Conexión a la base de datos
        ConexionDB conexion = new ConexionDB();
        
        String consulta = "SELECT nombrec2 FROM denuncia GROUP BY nombrec2 ORDER BY COUNT(nombrec2) DESC ";
        //Obtenemos resultados de la consulta
        ResultSet rs = conexion.creaTabla(consulta);
        
        try{
            rs.next();
            JOptionPane.showMessageDialog(null, "La cuenta que más ha denunciado es "+rs.getString("nombrec2"), "Resultado ", JOptionPane.INFORMATION_MESSAGE);
  
            conexion.cerrarConexionDB();
            
        }catch(SQLException e){
            e.printStackTrace(System.out);
            throw new RuntimeException(e);
        }    }//GEN-LAST:event_masDenuncianteActionPerformed

    private void masAntiguoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masAntiguoActionPerformed
        String consulta = "SELECT * FROM denuncia ORDER BY fecha ASC";
        //Creamos una nueva ventana de búsqueda
        ResultadoConsultasDenuncias res = new ResultadoConsultasDenuncias(consulta);
        //La añadimos al escritorio
        VentanaPrincipal.escritorio.add(res);
        //La situamos en el frente
        res.toFront();
        //La hacemos visible
        res.setVisible(true);    }//GEN-LAST:event_masAntiguoActionPerformed

    private void masRecienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masRecienteActionPerformed
        String consulta = "SELECT * FROM denuncia ORDER BY fecha DESC";
        //Creamos una nueva ventana de búsqueda
        ResultadoConsultasDenuncias res = new ResultadoConsultasDenuncias(consulta);
        //La añadimos al escritorio
        VentanaPrincipal.escritorio.add(res);
        //La situamos en el frente
        res.toFront();
        //La hacemos visible
        res.setVisible(true);
    }//GEN-LAST:event_masRecienteActionPerformed

    private void buscarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEquipoActionPerformed
        String consulta = "SELECT nombrec1,nombrec2,fecha,revisada FROM denuncia D,(SELECT nombre,nombreequipo FROM cuentapertenece NATURAL JOIN equipo) E WHERE E.nombre=D.nombrec1 and E.nombreequipo=\""+equipoBusc.getText()+"\"";
        System.out.println(consulta+"\n");

        //Creamos una nueva ventana de búsqueda
        ResultadoConsultasDenuncias res = new ResultadoConsultasDenuncias(consulta);
        //La añadimos al escritorio
        VentanaPrincipal.escritorio.add(res);
        //La situamos en el frente
        res.toFront();
        //La hacemos visible
        res.setVisible(true);
    }//GEN-LAST:event_buscarEquipoActionPerformed

    private void masDenunciadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masDenunciadoActionPerformed
        // Conexión a la base de datos
        ConexionDB conexion = new ConexionDB();
        
        String consulta = "SELECT nombrec1 FROM denuncia GROUP BY nombrec1 ORDER BY COUNT(nombrec1) DESC ";
        //Obtenemos resultados de la consulta
        ResultSet rs = conexion.creaTabla(consulta);
        
        try{
            rs.next();
            JOptionPane.showMessageDialog(null, "La cuenta más denunciada es "+rs.getString("nombrec1"), "Resultado ", JOptionPane.INFORMATION_MESSAGE);
  
            conexion.cerrarConexionDB();
            
        }catch(SQLException e){
            e.printStackTrace(System.out);
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_masDenunciadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarEquipo;
    private javax.swing.JTextField equipoBusc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton masAntiguo;
    private javax.swing.JButton masDenunciado;
    private javax.swing.JButton masDenunciante;
    private javax.swing.JButton masReciente;
    // End of variables declaration//GEN-END:variables
}
