/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddsimoba;

/**
 *
 * @author jesus
 */
public class HistorialDenuncias extends javax.swing.JInternalFrame {

    /**
     * Creates new form HistorialDenuncias
     */
    public HistorialDenuncias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaSimple = new javax.swing.JButton();
        busquedaAvanzada = new javax.swing.JToggleButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("HIstorial de Denuncias");

        busquedaSimple.setText("Búsqueda Simple");
        busquedaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaSimpleActionPerformed(evt);
            }
        });

        busquedaAvanzada.setText("Búsqueda Avanzada");
        busquedaAvanzada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaAvanzadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(busquedaSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(busquedaAvanzada)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busquedaSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(busquedaAvanzada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busquedaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaSimpleActionPerformed
        //Creamos una nueva ventana de búsqueda
        FormularioBusquedaSimpleDenuncias den = new FormularioBusquedaSimpleDenuncias();
        //La añadimos al escritorio
        VentanaPrincipal.escritorio.add(den);
        //La situamos en el frente
        den.toFront();
        //La hacemos visible
        den.setVisible(true);
    }//GEN-LAST:event_busquedaSimpleActionPerformed

    private void busquedaAvanzadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaAvanzadaActionPerformed
        //Creamos una nueva ventana de búsqueda
        FormularioBusquedaComplDenuncias den = new FormularioBusquedaComplDenuncias();
        //La añadimos al escritorio
        VentanaPrincipal.escritorio.add(den);
        //La situamos en el frente
        den.toFront();
        //La hacemos visible
        den.setVisible(true);
    }//GEN-LAST:event_busquedaAvanzadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton busquedaAvanzada;
    private javax.swing.JButton busquedaSimple;
    // End of variables declaration//GEN-END:variables
}
