package ddsimoba;


import ddsimoba.ConexionDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pablo
 */
public class ListarResultadosPartidas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarResultadosPartidas
     */
    public ListarResultadosPartidas() {
        initComponents();
        
        //Conectamos con la base de datos
        ConexionDB bd = new ConexionDB();
        
        //Modelo de tabla
        DefaultTableModel tabla = new DefaultTableModel();
        
        //Consulta
        String consulta = "SELECT * FROM juega";
        
        //Resultados
        ResultSet resultado = bd.creaTabla(consulta);
        
        //Indicar columnas
        tabla.setColumnIdentifiers(new Object[]{"idequipo1", "fecha", "idequipo2", "idpartida", "danoe1", "danoe2", "muertese1", "muertese2", "finalizada"});
    
        try {
            while(resultado.next()) {
                tabla.addRow(new Object[]{resultado.getString("idequipo1"), resultado.getString("fecha"), resultado.getString("idequipo2"), resultado.getString("idpartida"), resultado.getString("danoe1"), resultado.getString("danoe2"), resultado.getString("muertese1"), resultado.getString("muertese2"), resultado.getString("finalizada")});
            }
            
            this.panelResultados.setModel(tabla);
            
            bd.cerrarConexionDB();
        }
        catch(SQLException e){
            e.printStackTrace(System.out);
            throw new RuntimeException(e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelResultados = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idEquipo1", "fecha", "idEquipo2", "idpartida", "danoE1", "danoE2", "muertesE1", "muertesE2", "finalizada"
            }
        ));
        jScrollPane1.setViewportView(panelResultados);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable panelResultados;
    // End of variables declaration//GEN-END:variables
}
