/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddsimoba;

import java.sql.*;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pablo
 */
public class ListarResultadosPartidas extends javax.swing.JInternalFrame {

    /**
     * Creates new customizer ListarResultadosPartidas
     */
    public ListarResultadosPartidas() {
        initComponents();
        
        //Conectamos con la base de datos
        ConexionDB bd = new ConexionDB();
        
        //Modelo de tabla
        DefaultTableModel tabla = new DefaultTableModel();
        
        //Consulta
        String consulta = "SELECT * FROM juega";
        
        //Resultados
        ResultSet resultado = bd.creaTabla(consulta);
        
        //Indicar columnas
        tabla.setColumnIdentifiers(new Object[]{"idequipo1", "fecha", "idequipo2", "idpartida", "danoe1", "danoe2", "muertese1", "muertese2", "finalizada"});
    
        try {
            while(resultado.next()) {
                tabla.addRow(new Object[]{resultado.getString("idequipo1"), resultado.getString("fecha"), resultado.getString("idequipo2"), resultado.getString("idpartida"), resultado.getString("danoe1"), resultado.getString("danoe2"), resultado.getString("muertese1"), resultado.getString("muertese2"), resultado.getString("finalizada")});
            }
            
            this.panel_resultados.setModel(tabla);
            
            bd.cerrarConexionDB();
        }
        catch(SQLException e){
            e.printStackTrace(System.out);
            throw new RuntimeException(e);
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_resultados = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new java.awt.BorderLayout());

        panel_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(panel_resultados);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable panel_resultados;
    // End of variables declaration//GEN-END:variables
}
