/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ddsimoba;
import javax.swing.UIManager;
/**
 *
 * @author domin
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menuAltaUsuario = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        equipos = new javax.swing.JMenu();
        listarEquipo = new javax.swing.JMenuItem();
        menuTienda = new javax.swing.JMenu();
        listaArticulos = new javax.swing.JMenuItem();
        addArticulo = new javax.swing.JMenuItem();
        menuPartida = new javax.swing.JMenu();
        listarPartidas = new javax.swing.JMenuItem();
        bAñadirPartida = new javax.swing.JMenuItem();
        menuResultados = new javax.swing.JMenu();
        listarResultados = new javax.swing.JMenuItem();
        denuncias = new javax.swing.JMenu();
        revisarDenuncia = new javax.swing.JMenuItem();
        historialDenuncias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Información MOBA");
        setPreferredSize(new java.awt.Dimension(1250, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuUsuarios.setText("Usuarios");

        menuAltaUsuario.setText("Alta Usuario");
        menuAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAltaUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuAltaUsuario);

        jMenuItem1.setText("Listar Usuarios");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuUsuarios.add(jMenuItem1);

        jMenuBar1.add(menuUsuarios);

        equipos.setText("Equipos");

        listarEquipo.setText("Listar Equipo");
        listarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarEquipoActionPerformed(evt);
            }
        });
        equipos.add(listarEquipo);

        jMenuBar1.add(equipos);

        menuTienda.setText("Tienda");

        listaArticulos.setText("Listar Artículos");
        listaArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaArticulosActionPerformed(evt);
            }
        });
        menuTienda.add(listaArticulos);

        addArticulo.setText("Añadir nuevo artículo");
        addArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArticuloActionPerformed(evt);
            }
        });
        menuTienda.add(addArticulo);

        jMenuBar1.add(menuTienda);

        menuPartida.setText("Partida");

        listarPartidas.setText("Listar Partidas");
        listarPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPartidasActionPerformed(evt);
            }
        });
        menuPartida.add(listarPartidas);

        bAñadirPartida.setText("Añadir Partida");
        bAñadirPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirPartidaActionPerformed(evt);
            }
        });
        menuPartida.add(bAñadirPartida);

        jMenuBar1.add(menuPartida);

        menuResultados.setText("Resultados");

        listarResultados.setText("Listar Resultados");
        listarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarResultadosActionPerformed(evt);
            }
        });
        menuResultados.add(listarResultados);

        jMenuBar1.add(menuResultados);

        denuncias.setText("Denuncias");

        revisarDenuncia.setText("Revisar Denuncia");
        revisarDenuncia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisarDenunciaActionPerformed(evt);
            }
        });
        denuncias.add(revisarDenuncia);

        historialDenuncias.setText("Historial de Denuncias");
        historialDenuncias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialDenunciasActionPerformed(evt);
            }
        });
        denuncias.add(historialDenuncias);

        jMenuBar1.add(denuncias);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAltaUsuarioActionPerformed
        FormularioAltaUsuario form = new FormularioAltaUsuario();
        this.escritorio.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_menuAltaUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ListarUsuarios users = new ListarUsuarios();
        this.escritorio.add(users);
        users.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void listaArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaArticulosActionPerformed
        ListarArticulos articulos = new ListarArticulos();
        this.escritorio.add(articulos);
        articulos.setVisible(true);
    }//GEN-LAST:event_listaArticulosActionPerformed

    private void addArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArticuloActionPerformed
       FormularioAltaArticulo art = new FormularioAltaArticulo();
       this.escritorio.add(art);
       art.setVisible(true);
    }//GEN-LAST:event_addArticuloActionPerformed

    private void listarPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPartidasActionPerformed
        ListarPartidas partidas = new ListarPartidas();
        this.escritorio.add(partidas);
        partidas.setVisible(true);
    }//GEN-LAST:event_listarPartidasActionPerformed

    private void bAñadirPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirPartidaActionPerformed
        FormularioAltaPartida part = new FormularioAltaPartida();
        this.escritorio.add(part);
        part.setVisible(true);
    }//GEN-LAST:event_bAñadirPartidaActionPerformed

    private void listarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarResultadosActionPerformed
        ListarResultadosPartidas lista = new ListarResultadosPartidas();
        this.escritorio.add(lista);
        lista.setVisible(true);
    }//GEN-LAST:event_listarResultadosActionPerformed

    private void listarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarEquipoActionPerformed
        ListarEquipos lista = new ListarEquipos();
        this.escritorio.add(lista);
        lista.setVisible(true);
    }//GEN-LAST:event_listarEquipoActionPerformed

    private void historialDenunciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialDenunciasActionPerformed
        HistorialDenuncias historial = new HistorialDenuncias();
        this.escritorio.add(historial);
        historial.setVisible(true);
    }//GEN-LAST:event_historialDenunciasActionPerformed

    private void revisarDenunciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisarDenunciaActionPerformed
        RevisarDenuncias den = new RevisarDenuncias();
        this.escritorio.add(den);
        den.setVisible(true);
    }//GEN-LAST:event_revisarDenunciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addArticulo;
    private javax.swing.JMenuItem bAñadirPartida;
    private javax.swing.JMenu denuncias;
    private javax.swing.JMenu equipos;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem historialDenuncias;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listaArticulos;
    private javax.swing.JMenuItem listarEquipo;
    private javax.swing.JMenuItem listarPartidas;
    private javax.swing.JMenuItem listarResultados;
    private javax.swing.JMenuItem menuAltaUsuario;
    private javax.swing.JMenu menuPartida;
    private javax.swing.JMenu menuResultados;
    private javax.swing.JMenu menuTienda;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenuItem revisarDenuncia;
    // End of variables declaration//GEN-END:variables
}
